# Generated by Django 5.0.1 on 2024-01-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_matchresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
